version: '3.8'

services:
  backend:
    build: ./backend
    container_name: innoevent-backend
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./backend:/app
      - ./backend/innoevent.db:/app/innoevent.db
    command: python main.py
    networks:
      - innoevent-network

  frontend:
    build: ./frontend
    container_name: innoevent-frontend
    ports:
      - "3000:3000"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: python app.py
    networks:
      - innoevent-network

networks:
  innoevent-network:
    driver: bridge
